"""Generate an enriched VoID description for the Elites Suisses endpoint.

Queries the live endpoint for:
- Total triples / entities
- Per-class instance counts (void:classPartition)
- Per-(class, predicate) counts (void:classPartition / void:propertyPartition)
- Overall predicate counts (void:propertyPartition)

Writes a Turtle file. SparqlVoidShapesLoader consumes this to build ShEx
class shapes that the validator and the system prompt benefit from.

Run from the sparql-llm/ directory:
    uv run python scripts/enrich_void.py

Re-run whenever the underlying graph changes shape.
"""

from __future__ import annotations

import urllib.parse
import urllib.request
import json
from pathlib import Path

ENDPOINT = "https://swiss-elites.lod4hss.cloud/wisski/endpoint/default"
GRAPH = "https://swiss-elites.lod4hss.cloud/resource/"
OUT_PATH = Path(__file__).parent.parent / "data" / "elites-suisses-void.ttl"


def sparql_select(query: str) -> list[dict]:
    """Run a SELECT and return the bindings list."""
    url = ENDPOINT + "?" + urllib.parse.urlencode({"query": query})
    req = urllib.request.Request(url, headers={"Accept": "application/sparql-results+json"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)["results"]["bindings"]


PREFIXES = {
    "http://www.cidoc-crm.org/cidoc-crm/": "crm",
    "https://sdhss.org/ontology/social-life-core/": "sdh-slc",
    "https://sdhss.org/ontology/shortcuts/": "sdh-short",
    "https://sdhss.org/ontology/core/": "sdh",
    "https://sdhss.org/ontology/crm-supplement/": "crm-sup",
    "https://swiss-elites.lod4hss.cloud/resource/": "swel",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#": "rdf",
    "http://www.w3.org/2000/01/rdf-schema#": "rdfs",
    "http://www.w3.org/2002/07/owl#": "owl",
    "http://www.w3.org/2001/XMLSchema#": "xsd",
    "http://rdfs.org/ns/void#": "void",
    "http://purl.org/dc/terms/": "dct",
}


def shorten(iri: str) -> str:
    """Return a prefixed name if any prefix matches, otherwise <full IRI>."""
    for ns, p in PREFIXES.items():
        if iri.startswith(ns):
            local = iri[len(ns):]
            if local:
                return f"{p}:{local}"
    return f"<{iri}>"


def main() -> None:
    print(f"Querying {ENDPOINT} …")

    triples = int(sparql_select(
        f"SELECT (COUNT(*) AS ?n) WHERE {{ GRAPH <{GRAPH}> {{ ?s ?p ?o }} }}"
    )[0]["n"]["value"])
    entities = int(sparql_select(
        f"SELECT (COUNT(DISTINCT ?s) AS ?n) WHERE {{ GRAPH <{GRAPH}> {{ ?s ?p ?o }} }}"
    )[0]["n"]["value"])
    print(f"  triples  = {triples}")
    print(f"  entities = {entities}")

    class_rows = sparql_select(
        f"SELECT ?c (COUNT(*) AS ?n) WHERE {{ GRAPH <{GRAPH}> {{ ?s a ?c }} }} GROUP BY ?c ORDER BY DESC(?n)"
    )
    classes = [(r["c"]["value"], int(r["n"]["value"])) for r in class_rows]
    print(f"  classes  = {len(classes)} ({[shorten(c) for c, _ in classes]})")

    prop_rows = sparql_select(
        f"SELECT ?p (COUNT(*) AS ?n) WHERE {{ GRAPH <{GRAPH}> {{ ?s ?p ?o }} }} GROUP BY ?p ORDER BY DESC(?n)"
    )
    props = [(r["p"]["value"], int(r["n"]["value"])) for r in prop_rows]
    print(f"  predicates = {len(props)}")

    class_prop_rows = sparql_select(
        f"SELECT ?c ?p (COUNT(*) AS ?n) WHERE {{ GRAPH <{GRAPH}> {{ ?s a ?c ; ?p ?o }} }} "
        f"GROUP BY ?c ?p ORDER BY ?c DESC(?n)"
    )
    by_class: dict[str, list[tuple[str, int]]] = {}
    for r in class_prop_rows:
        by_class.setdefault(r["c"]["value"], []).append((r["p"]["value"], int(r["n"]["value"])))

    lines: list[str] = []
    lines.append("# Auto-generated by scripts/enrich_void.py — DO NOT EDIT BY HAND.")
    lines.append("# Run `uv run python scripts/enrich_void.py` to refresh.")
    lines.append("# Source endpoint: " + ENDPOINT)
    lines.append("")
    for ns, p in PREFIXES.items():
        lines.append(f"@prefix {p}: <{ns}> .")
    lines.append("")
    lines.append("<http://swiss-elites.lod4hss.cloud/void> a void:Dataset ;")
    lines.append(f'    void:uriSpace "{GRAPH}" ;')
    lines.append(f'    void:triples "{triples}"^^xsd:integer ;')
    lines.append(f'    void:entities "{entities}"^^xsd:integer ;')
    lines.append(f"    void:sparqlEndpoint <{ENDPOINT}> ;")
    lines.append(f"    void:exampleResource swel:p50001 ;")

    if classes:
        cls_list = ", ".join(shorten(c) for c, _ in classes)
        lines.append(f"    void:classes {cls_list} ;")
    if props:
        prop_list = ", ".join(shorten(p) for p, _ in props)
        lines.append(f"    void:properties {prop_list} ;")

    for c, n in classes:
        lines.append("    void:classPartition [")
        lines.append(f"        void:class {shorten(c)} ;")
        lines.append(f'        void:entities "{n}"^^xsd:integer ;')
        cprops = by_class.get(c, [])
        for i, (p, pn) in enumerate(cprops):
            lines.append("        void:propertyPartition [")
            lines.append(f"            void:property {shorten(p)} ;")
            lines.append(f'            void:triples "{pn}"^^xsd:integer')
            lines.append("        ]" + (" ;" if i < len(cprops) - 1 else ""))
        lines.append("    ] ;")

    for i, (p, n) in enumerate(props):
        lines.append("    void:propertyPartition [")
        lines.append(f"        void:property {shorten(p)} ;")
        lines.append(f'        void:triples "{n}"^^xsd:integer')
        lines.append("    ]" + (" ;" if i < len(props) - 1 else " ."))

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n  Wrote {OUT_PATH} ({len(lines)} lines, {OUT_PATH.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
